[project]
name = "math-utils"
version = "0.1.0"
description = "Mathematical utility functions"
readme = "README.md"
license = {text = "MIT"}
authors = [
    { name = "Your Name", email = "your.name@example.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
testing = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[project.scripts]
math-calc = "math_utils.cli:main"

[build-system]
requires = ["hatchling", "editables"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/math_utils"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = [
    "-ra",
    "--strict-markers",
    "--cov=math_utils",
    "--cov-report=term-missing",
    "--cov-report=html",
]

[tool.coverage.run]
source = ["src/math_utils"]
